# Generated by Django 5.0.2 on 2024-04-12 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tag_answer_ismoderate_alter_answer_questionid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tagId',
        ),
    ]
