# Generated by Django 5.0.2 on 2024-04-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_question_tagid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=300, unique=True),
        ),
    ]
